### ISSUE TITLE
Humanoid

### ISSUE THREAD

**Issue by keezpipslab** [SonySemiconductorSolutions/tof-ar-samples-ar#2]
Hello Tof.

The Humanoid example is missing from these examples. Is this on purpose ? I am very interested in this example.

Thanks,
Keez

**Comment by HirotakaGoto** [comment]
Thank you for your interest in ToF AR. 

Yes, unfortunately the Humanoid app example is not included on purpose. 
We can't publish the source code for this app because Humanoid app contained in Lab uses a proprietary technology to make the avatar operate smoothly. 
You could develop a new application similar to Humanoid app using ToF AR. 
If you are interested in using the Humanoid app for business use, please contact our business division below:
https://developer.sony.com/develop/tof-ar/contact-us

ToF AR team
